### ISSUE TITLE
 𝙰𝚜𝚔 𝙼𝚎 𝙰𝚋𝚘𝚞𝚝 𝙰𝚗𝚢𝚝𝚑𝚒𝚗𝚐 ?

### ISSUE THREAD

**Issue by vishalpande** [vishalpande/vishalpande#1]

**Comment by Jay-Karia** [comment]
I have a confusion selecting the best framework for Mobile Development, Flutter or React Native.
Can you please help me out.

**Comment by vishalpande** [comment]
Hii Jay,

Both flutter and react native are powerful framework.The choice between
flutter and react native depends on specific needs and requirements.If you
are prioritize performance flutter might be the best.If you prioritize
easier learning curve and and number of available libraries and plugins,
React Native might be better for you.I think you will go for react native
but its all depends on you . I will share you a link please go through it.
For better understanding.

https://www.simplilearn.com/tutorials/reactjs-tutorial/flutter-vs-react-native#:~:text=React%20Native%3A%20React%20Native%20is%20based%20more%20on%20native%20components,%2C%20platform%2C%20and%20interactive%20widgets
.

**Comment by Jay-Karia** [comment]
Great 👍🏿
Thank you very much 🙂
